spring.application.name=logengine

spring.datasource.url=jdbc:mysql://localhost:3306/logengine
spring.datasource.username=root
spring.datasource.password=mouna

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Server
server.port=8080